app:
  token:
    secret: gbfgnhgmjgmgmfvfpgodfkgobkdlfvkdzlvdsfodrkgitphoksrphogbks;glvsfkgvs;ldogkbs;zdlgvksd;lvogksfgol;aekodfkgsogksrfgfkgdflgkdgl
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1111
  jpa:
    hibernate:
      ddl-auto: none
